RumahSakit/urls.py
from django.shortcuts import render

from django.urls import path

from . import views

app_name = 'RumahSakit'

urlpatterns = [
    path('list_rumah_sakit', views.list_rs, name='list_rs'),
    path('pendaftar', views.list_pendaftar, name='pendaftar'),
]

TKPPW/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tk1.urls')),
    path('', include('RumahSakit.urls')),
    path('donasi/', include('donasi.urls')),
    path('admin-rs/', include('admin_rs.urls')),
    path('', include('Pengalaman.urls')),
    path('', include('screeningCovid.urls')),
    path('', include('Riwayat.urls')),
    path('', include('login.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_account, name='login'),
    path('logout/', views.logout_account, name='logout')
]

screeningCovid/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name = 'screeningCovid'

urlpatterns = [
    path('screening', views.bantuan, name='screeningCovid'),
    path('daftarbantuan', views.pendaftar_bantuan, name='daftarbantuan'),
    #path('bukti-tf-swab', views.bukti, name='bukti-tf-swab'),
]

tk1/urls.py
from django.urls import path

from . import views
app_name='home'

urlpatterns = [
    path('', views.home, name='home'),
]

screeningCovid/models.py
from django.db import models

# Create your models here.
class Isian(models.Model):
    nama = models.CharField('Nama', max_length = 50) 
    nohp = models.PositiveIntegerField('Nomor Hp')
    alamat = models.CharField('Alamat', max_length = 3000)

    def __str__(self):
        return self.nama

screeningCovid/forms.py
from django import forms
from .models import Isian

class Form_bantuan(forms.ModelForm):
    class Meta:
        model = Isian
        fields = ('nama', 'nohp', 'alamat')

        widgets = {
            'nama': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder': "Isi dengan nama lengkapmu!"}),

            'nohp': forms.NumberInput(attrs={
                'class':'form-control',
                'placeholder': "Isi dengan nomer yang dapat dihubungi!"}),

            'alamat': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder': "Isi dengan alamat lengkap!"}),
        }

screeningCovid/views.py
from django.shortcuts import render, redirect
from .models import Isian
from .forms import Form_bantuan

# Create your views here.
def bantuan(request):
    if request.method == "POST":
        form = Form_bantuan(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'haltidak.html')
    else :
        form = Form_bantuan()
    return render(request, 'halscreening.html', {'form': form})

def pendaftar_bantuan(request):
    hasilForm = Isian.objects.all()
    return render(request,'haldaftar.html',{'hasilForm': hasilForm})

screeningCovid/templates/haldaftar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<table class="table">
    <thead style="background-color:  #8BA6B9;">
        <tr style="color: white;">
            <th scope="col">Nama</th>
            <th scope="col">Nomor Hp</th>
            <th scope="col">Alamat</th>
        </tr>
    </thead>
    {% for hasil in hasilForm %}
    <tbody>
        <tr>
            <td>{{hasil.nama}}</td>
            <td>{{hasil.nohp}}</td>
            <td>{{hasil.alamat}}</td>
    </tbody>
    {% endfor %}
</table>
{%endblock%}

screeningCovid/templates/halscreening.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<div>
    <h1 id="judul_screening" style="text-align: center;">Daftar Untuk Penjemputan Pasien Covid</h1>
    {% if user.is_authenticated %}
    <div class="container screening" style="margin-top:1rem;">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center" style="margin: 15px;">
                    <form method="POST" class="post-form" enctype="multipart/form-data">
                        {% for i in form %}
                        {% csrf_token %}
                            <div style="font-size: 20px; font-weight: bold; text-align: left;">{{i.label_tag}}</div>
                            <div>{{i}}</div>
                        {% endfor %}
                        <div class="center-items" style="margin-top: 20px;">
                            <input type="submit" class="btn btn-primary" value="Submit">
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div> 
    {% else %}
    <div class="container screening" style="margin-top:1rem;">
        <div class="row">
            <div class="col-lg-12">
                <h1 style="text-align: center; margin-top: 75px;"><a href="{% url 'login:login' %}">Anda harus login terlebih dahulu supaya dapat mengisi form Penjemputan</a></h1>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

screeningCovid/templates/haltidak.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style=" margin-top: 5rem; position: relative; color: black;">
    <div class="card mx-auto" id="kartu1" style="background-color: #F7F7F2; border-radius: 70px;">
        <div class="card-body" style="position: relative; text-align: left; font-style: normal; font-weight: bold; font-size: 24px; margin-left: 50px;">
            Harap tenang, kami akan segara mengkonfirmasi permohonan anda</br>
            dan akan menghubungi anda lewat nomor yang telah anda berikan.
        </div>    
    </div>
</div>
{% endblock content %}
                    

screeningCovid/templates/halyatidak.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style=" margin-top: 5rem; position: relative; color: black;">
    <div class="card mx-auto" id="kartu1" style="background-color: #F7F7F2; border-radius: 70px;">
        <div class="card-body" style="position: relative; text-align: left; font-style: normal; font-weight: bold; font-size: 24px; margin-left: 50px;">
            Silahkan melakukan isolasi mandiri , jika ada keluhan mengenai kesehatan</br>
            anda segera periksakan ke fasilitas pelayanan kesehatan terdekat.</br>
            Daftar Rumah sakit rujukan dapat dilihat <a href="{% url 'RumahSakit:list_rs' %}"> disini.
    </div>
</div>
{% endblock content %}
                    

screeningCovid/templates/halyaya.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style=" margin-top: 5rem; position: relative; color: black;">
    <div class="card mx-auto" id="kartu1" style="background-color: #F7F7F2; border-radius: 70px;">
        <div class="card-body" style="position: relative; text-align: left; font-style: normal; font-weight: bold; font-size: 24px; margin-left: 50px;">
            Jagalah pola hidup sehat dengan tetap menjaga kebersihan. Jangan lupa untuk tetap menjalankan 4M dan 1B, yaitu :</br> 
            1. Menjaga Jarak</br>
            2. Memakai Masker</br>
            3. Mencuci Tangan</br>
            4. Makan Bergizi</br>
            5. Berolahraga
        </div>
    </div>
</div>
{% endblock content %}