TKPPW/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tk1.urls')),
    path('', include('RumahSakit.urls')),
    path('donasi/', include('donasi.urls')),
    path('admin-rs/', include('admin_rs.urls')),
    path('', include('Pengalaman.urls')),
    path('', include('screeningCovid.urls')),
    path('', include('Riwayat.urls')),
    path('', include('login.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_account, name='login'),
    path('logout/', views.logout_account, name='logout')
]

tk1/urls.py
from django.urls import path

from . import views
app_name='home'

urlpatterns = [
    path('', views.home, name='home'),
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class registerAccount(UserCreationForm):
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

login/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import *
from .forms import registerAccount

# Create your views here.
def register(request):
	form = registerAccount()
	if request.method == 'POST':
		form = registerAccount(request.POST)
		if form.is_valid():
			form.save()
			return redirect('login:login')

	context = {'form':form}
	return render(request, 'register.html', context)

def login_account(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('home:home')
		else:
			messages.info(request, "username or password invalid")

	return render(request, 'loginaccount.html')

def logout_account(request):
	logout(request)
	return redirect('home:home')

login/templates/loginaccount.html
{% extends 'base.html' %}
{% load static %}
{%block content%}

<form method="POST" class="post-form; text-center" enctype="multipart/form-data" style="margin-top: 2rem;">
 {% csrf_token %}
   <div style="font-size: 20px;">Username</div>
   <input type="text" name="username" id="form-register"></input>
   <div style="font-size: 20px;">Password</div>
   <input type="password" name="password" id="form-register"></input>
   <div class="text-center">
   	<br>
   <p>Don't have an account? <a href="{% url 'login:register' %}">Sign up here </a></p>
   <button class="btn btn-primary" role="button" type="submit">submit</button>
   </div>
   </div>
</form>

{% endblock %}

login/templates/register.html
{% extends 'base.html' %}
{% load static %}
{%block content%}
<div class="container" style="width:20%; margin-top: 1rem">
<div class="row justify-content-center">
<div>
<form method="POST" class="post-form; text-center" style="font-size: 20px;" enctype="multipart/form-data">
                  {%for i in form%}
                  {%csrf_token%}
                     <div style="font-size: 20px">{{i.label_tag}}</div>
                      <div id="form-register">{{i}}</div>
                    {%endfor%}
                      <div class="text-center">
                        <br>
                        <button class="btn btn-primary" role="button" type="submit">sign up</button>
                      </div>
                  
                    </form>
                  </div>
</div>
</div>
{% endblock %}